In [1]:
# Generate a random normal distribution of size 2x3

from numpy import random
x = random.normal(size=(2,3))
print(x)


[[-1.07110883  0.81310942 -0.50716854]
 [ 0.58288218 -1.85590059  0.05787569]]


In [3]:
# Generate a random normal distribution of size 2x3 with mean at 1 and starderd deviation of 2:

from numpy import random
x = random.normal(loc=1,scale=2,size=(2,3))
print(x)

[[ 3.39469797  1.09168675 -2.03801237]
 [ 1.29092318  2.33049132  2.26106762]]


In [ ]:
# Visualization of Normal Distribution

from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.displot(random.normal(size=1000), hist=False)

plt.show()